services:
  trex:
    build:
      context: ../../../
      dockerfile: Dockerfile.trex
    pull_policy: never
    command: npm run watch
    ports:
      - 8001:8001
      - 25432:5432
    volumes:
      - ../../../core:/usr/src/core
      - ../../../package.json:/usr/src/package.json
    environment:
      LOCAL_DEBUG: "true"
      DATABASE_CREDENTIALS: ${DATABASE_CREDENTIALS}
      PLUGIN_BASE_PATH: "./plugins"
