export const _env = Deno.env.toObject();
export const env = {
    PRFECT_API_URL: _env.PREFECT_API_URL,
    TLS__INTERNAL__CRT: _env.TLS__INTERNAL__CRT?.replace(/\\n/g, '\n'),
    TLS__INTERNAL__KEY: _env.TLS__INTERNAL__KEY?.replace(/\\n/g, '\n'),
    TLS__INTERNAL__CA_CRT: _env.TLS__INTERNAL__CA_CRT?.replace(/\\n/g, '\n'),
    SERVICE_ROUTES: JSON.parse(_env.SERVICE_ROUTES),
    GATEWAY_WO_PROTOCOL_FQDN: _env.GATEWAY__WO_PROTOCOL_FQDN || "localhost:41100",
    LOGTO_CLIENT_ID: _env.LOGTO__CLIENT_ID,
    LOGTO_SCOPE: _env.LOGTO__SCOPE,
    APP_LOCALE: _env.APP_LOCALE,
    IDP_RELYING_PARTY: _env.IDP__RELYING_PARTY,
    PLUGINS_JSON: _env.PLUGINS__JSON,
    DB_CREDENTIALS_PUBLIC_KEYS: _env.DB_CREDENTIALS__PUBLIC_KEYS,
    GATEWAY_IDP_AUTH_TYPE: _env.GATEWAY__IDP_AUTH_TYPE,
    LOGTO_ISSUER: _env.LOGTO__ISSUER,
    LOGTO_AUDIENCES: _env.LOGTO__AUDIENCES,
    LOGTO_SVC_CLIENT_ID: _env.LOGTO__SVC_CLIENT_ID,
    LOGTO_SVC_CLIENT_SECRET: _env.LOGTO__SVC_CLIENT_SECRET,
    NODE_ENV: _env.NODE_ENV,
    LOGTO_CLIENT_SECRET: _env.LOGTO__CLIENT_SECRET,
    LOGTO_TOKEN_URL: _env.LOGTO__TOKEN_URL,
    LOGTO_RESOURCE_API: _env.LOGTO__RESOURCE_API,
    GATEWAY_IDP_SUBJECT_PROP: _env.GATEWAY__IDP_SUBJECT_PROP,
    BASE_PATH: "./plugins"

}
console.log(env);

