---
openapi: 3.0.0
servers:
- url: http://petstore.swagger.io/v2
info:
  description: This is a sample server Petstore server. For this sample, you can use
    the api key `special-key` to test the authorization filters.
  version: 1.0.0
  title: OpenAPI Petstore
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  
  "/pet/*":
    summary: Update an existing pet
    description: ''
    get:
      operationId: get
      responses:
        default:
          description: OK
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      - petstore_auth:
        - admin:pets
    post:
      operationId: get
      responses:
        default:
          description: OK
      security:
      - petstore_auth:
        - write:pets
        - read:pets
    put:
      operationId: get
      responses:
        default:
          description: OK
      security:
      - petstore_auth:
        - write:pets
        - read:pets
    delete:
      operationId: get
      responses:
        default:
          description: OK
      security:
      - petstore_auth:
        - write:pets
        - read:pets
components:
  requestBodies:
    Pet:
      content:
        application/json: {}
      description: Pet object that needs to be added to the store
      required: true
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
