[package]
name = "trex_core"
version = "0.1.0"
authors = [""]
edition = "2021"
license = "Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
trex.workspace = true

sb_core.workspace = true

libc.workspace = true
serde.workspace = true