name: Run Authorization Tests

on:
  workflow_dispatch: # Allow manual triggering
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop

jobs:
  test:
    name: Run Authorization Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.43.1

      - name: Run Authorization Tests
        run: deno test --no-check --allow-env ./core/server/auth/authz.test.ts
