name: Docker Build and Push to Azure CR

on:
  push:
    branches:
      - develop
      - p-hoffmann/ghcr
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - AZ_REGISTRY_REPOSITORY: d2e-trex-base
            context: .
            dockerfile: ./Dockerfile.trex

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
          
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setting up variables
        id: setup
        run: |
          DOCKER_IMG_TAG_NAME=$(echo $(git rev-parse --short HEAD))
          GIT_BRANCH_NAME=$(echo ${{ github.ref }} )
          ACR_IMAGE_PUSH=false
          if [[ ${{ github.event_name }} == "push" ]]; then 
            ACR_IMAGE_PUSH=true
          fi
          echo DOCKER_IMG_TAG_NAME=$DOCKER_IMG_TAG_NAME >> $GITHUB_OUTPUT 
          echo GIT_BRANCH_NAME="${GIT_BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo ACR_IMAGE_PUSH="${ACR_IMAGE_PUSH}" >> $GITHUB_OUTPUT

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: Build and Push
        id: build-push2
        uses: docker/build-push-action@v6
        with:
          push: ${{ steps.setup.outputs.ACR_IMAGE_PUSH }}
          platforms: "linux/amd64"
          tags: ghcr.io/data2evidence/${{ matrix.AZ_REGISTRY_REPOSITORY }}:develop
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AZ_REGISTRY_NAME }}.azurecr.io
          username: ${{ vars.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}
        
      - name: Build and Push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          push: ${{ steps.setup.outputs.ACR_IMAGE_PUSH }}
          platforms: "linux/amd64"
          tags: ${{ vars.AZ_REGISTRY_NAME }}.azurecr.io/${{ matrix.AZ_REGISTRY_REPOSITORY }}:develop
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}

      - name: Output Summary 
        run: | 
          echo "### Output summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "Job Status: ${{ job.status }} " >> $GITHUB_STEP_SUMMARY
          echo "GIT_BRANCH_NAME: ${{ steps.setup.outputs.GIT_BRANCH_NAME }} " >> $GITHUB_STEP_SUMMARY
          echo "GIT_COMMIT_ARG: ${{ github.sha }} " >> $GITHUB_STEP_SUMMARY
          echo "AZ_REGISTRY_REPOSITORY: ${{ matrix.AZ_REGISTRY_REPOSITORY }} " >> $GITHUB_STEP_SUMMARY
          echo "ACR_IMAGE_PUSH: ${{ steps.setup.outputs.ACR_IMAGE_PUSH }} " >> $GITHUB_STEP_SUMMARY
          echo "DOCKER_IMG_TAG_NAME: ${{ steps.setup.outputs.DOCKER_IMG_TAG_NAME }} " >> $GITHUB_STEP_SUMMARY
