name: build npm pkg

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop
      - npmci

env:
  GIT_CI_BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rm npmrc
        run: rm .npmrc
      - name: Build
        run: cargo build --profile release
      - name: cp
        run: cp target/release/edge-runtime trex
      - name: Update version
        run: jq --arg v "-$(date +%s)-$GITHUB_SHA" '.version+=$v' package.json > tmppkg; mv tmppkg package.json
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@data2evidence"
      - name: Publish
        run: |
          if [[ $GIT_CI_BRANCH_NAME == 'npmci' || $GIT_CI_BRANCH_NAME == 'develop' ]]; then 
            npm publish
          else 
            npm publish --dry-run
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v5
        if: github.ref_name == 'npmci' || github.ref_name == 'develop'
        with:
          package-name: "trex"
          package-type: "npm"
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"
